---
- name: Add VirtualBox repository to yum
  yum_repository:
    name: virtualbox
    description: EPEL YUM repo
    baseurl: "{{ virtualbox_url }}/rpm/el/$releasever/$basearch"
    gpgkey: "{{ virtualbox_url }}"
    gpgcheck: yes
    enabled: no

- name: Install VirtualBox dependencies
  yum:
    state: present
    name:
      - gcc
      - dkms
      - make
      - qt
      - libgomp
      - patch
      - kernel-headers
      - kernel-devel
      - binutils
      - glibc-headers
      - glibc-devel

- name: Install VirtualBox
  yum:
    name: "VirtualBox-{{ vbox_version }}"
    enablerepo: virtualbox
    state: present
